# Generated by Django 4.2.20 on 2025-03-29 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
